# 一、ndarray
## 1.ndarray特性
### 1.1 多维性

In [1]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5]) #一维数组
print(arr)
print(arr.ndim) #输出数组维度

In [ ]:
arr = np.array([[1,2,3],[4,5,6]]) #二维数组, 需要各行对齐
print(arr)
print(arr.ndim) #输出数组维度

### 1.2同质性

In [ ]:
arr = np.array([1,'hello']) #1被转化为与hello同质的字符串
arr2 = np.array([1, 1.5])  #1被转化为与1.5同质的浮点数
print(arr)
print(arr2)

## 2.ndarray的属性

In [ ]:
arr0 = np.array(1) #0维数组

print('0维数组的形状:', arr0.shape)
print('0维数组维度:', arr0.ndim)
print('0维数组元素个数:', arr0.size)
print('0维数组元素数据类型:', arr0.dtype)
print('0维数组的转置',arr0.T)
print('单个元素占用的内存字节数', arr0.itemsize)
print('数组总内存占用', arr0.nbytes)
print('内存存储方式',arr0.flags)


In [ ]:
arr1 = np.array([1,2])

print('1维数组的形状:', arr1.shape)
print('1维数组维度:', arr1.ndim)
print('1维数组元素个数:', arr1.size)
print('1维数组元素数据类型:', arr1.dtype)
print('1维数组的转置',arr1.T)
print('单个元素占用的内存字节数', arr1.itemsize)
print('数组总内存占用', arr1.nbytes)
print('内存存储方式',arr1.flags)


In [ ]:
arr2 = np.array([[1,2,4.0],[3,4,5]])

print('2维数组的形状:', arr2.shape)
print('2维数组维度:', arr2.ndim)
print('2维数组元素个数:', arr2.size)
print('2维数组元素数据类型:', arr2.dtype)
print('2维数组的转置',arr2.T)
print('单个元素占用的内存字节数', arr2.itemsize)
print('数组总内存占用', arr2.nbytes)
print('内存存储方式',arr2.flags)

## 3.ndarray创建方法

In [ ]:
# 基础创建方法
list = [[1,2,3],[4,5,6]]
arr = np.array(list, dtype=np.float64) #可以使用dtype参数指定元素数据类型
print(arr)

In [ ]:
# copy
arr_copy = np.copy(arr) # 仅复制数组内容
print(arr_copy)
arr[0][0] = 8.0
print(arr_copy)

In [ ]:
# 预定义形状
# 全0 全1 未初始化 固定值
arr = np.zeros((2,3))
print(arr)
print(arr.dtype) # 默认float64
arr1 = np.zeros((2,3), dtype=np.int64)
print(arr1.dtype)

In [ ]:
arr = np.zeros((10,), dtype=np.int64)
print(arr)

In [ ]:
#全1
arr = np.ones((10,), dtype=np.int64)
print(arr)

In [ ]:
#未初始化
arr = np.empty((3,)) #数值随机
print(arr)

In [ ]:
# 固定值
arr = np.full((3,4), 5, dtype=np.float64)
print(arr)

In [ ]:
arr = np.full((3,4), 5, dtype=np.int64)
arr_z = np.zeros_like(arr) # 使用arr的形状和元素类型
print(arr_z)
arr_o = np.ones_like(arr)
print(arr_o)
arr_e = np.empty_like(arr)
print(arr_e)
arr_f = np.full_like(arr, 6.0) # 虽然使用6.0, 但创建该数组依旧使用arr的元素类型
print(arr_f)

In [4]:
# 等差数列数组
arr = np.arange(1,9,2) # start, end, step 不包含end
print(arr)

[1 3 5 7]


In [9]:
# 等间隔数组
arr = np.linspace(0,10,5) #把0到10等分
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [10]:
# 对数间隔数组
arr = np.logspace(0,4,3,base=2) # 计算以2为底的指数
print(arr)

[ 1.  4. 16.]


In [12]:
# 特殊矩阵
# 单位矩阵：主对角线上的元素为1，其余元素都为0
arr = np.eye(3,dtype=np.int64)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [13]:
# 对角矩阵: 主对角线上的元素不全为0, 其余元素全为0
arr = np.diag([1,2,2])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 2]]


In [16]:
# 随机矩阵:
arr = np.random.rand(2,3) # 随机数默认0-1
print(arr)

[[0.71302654 0.97902316 0.39475805]
 [0.69938567 0.90412978 0.19375109]]


In [21]:
# 随机浮点数矩阵 指定随机数范围:
arr = np.random.uniform(2,5,(2,3))
print(arr)

[[2.64455274 2.92255136 3.87946755]
 [3.31858483 3.09191001 4.98506301]]


In [22]:
# 随机整数矩阵 指定随机数范围:
arr = np.random.randint(2,5,(2,3))
print(arr)

[[4 3 2]
 [2 2 2]]


In [26]:
# 随机矩阵 元素服从标准正态分布: 元素主要分布在-3 - 3之间
arr = np.random.randn(2,5)
print(arr)

[[-0.71419411 -1.56195377 -0.15544838  0.94127523 -1.44492326]
 [-1.1071639   1.49240243 -1.73854391 -3.17717754 -0.42894046]]


In [30]:
# 设置随机种子
np.random.seed(30)
arr = np.random.randint(2,10,(2,3))
print(arr)

[[7 7 7]
 [7 6 6]]
