# 一、ndarray
## 1.ndarray特性
### 1.1 多维性

In [2]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5]) #一维数组
print(arr)
print(arr.ndim) #输出数组维度

[1 2 3 4 5]
1


In [3]:
arr = np.array([[1,2,3],[4,5,6]]) #二维数组, 需要各行对齐
print(arr)
print(arr.ndim) #输出数组维度

[[1 2 3]
 [4 5 6]]
2


### 1.2同质性

In [4]:
arr = np.array([1,'hello']) #1被转化为与hello同质的字符串
arr2 = np.array([1, 1.5])  #1被转化为与1.5同质的浮点数
print(arr)
print(arr2)

['1' 'hello']
[1.  1.5]


## 2.ndarray的属性

In [5]:
arr0 = np.array(1) #0维数组

print('0维数组的形状:', arr0.shape)
print('0维数组维度:', arr0.ndim)
print('0维数组元素个数:', arr0.size)
print('0维数组元素数据类型:', arr0.dtype)
print('0维数组的转置',arr0.T)
print('单个元素占用的内存字节数', arr0.itemsize)
print('数组总内存占用', arr0.nbytes)
print('内存存储方式',arr0.flags)


0维数组的形状: ()
0维数组维度: 0
0维数组元素个数: 1
0维数组元素数据类型: int64
0维数组的转置 1
单个元素占用的内存字节数 8
数组总内存占用 8
内存存储方式   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [6]:
arr1 = np.array([1,2])

print('1维数组的形状:', arr1.shape)
print('1维数组维度:', arr1.ndim)
print('1维数组元素个数:', arr1.size)
print('1维数组元素数据类型:', arr1.dtype)
print('1维数组的转置',arr1.T)
print('单个元素占用的内存字节数', arr1.itemsize)
print('数组总内存占用', arr1.nbytes)
print('内存存储方式',arr1.flags)


1维数组的形状: (2,)
1维数组维度: 1
1维数组元素个数: 2
1维数组元素数据类型: int64
1维数组的转置 [1 2]
单个元素占用的内存字节数 8
数组总内存占用 16
内存存储方式   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [7]:
arr2 = np.array([[1,2,4.0],[3,4,5]])

print('2维数组的形状:', arr2.shape)
print('2维数组维度:', arr2.ndim)
print('2维数组元素个数:', arr2.size)
print('2维数组元素数据类型:', arr2.dtype)
print('2维数组的转置',arr2.T)
print('单个元素占用的内存字节数', arr2.itemsize)
print('数组总内存占用', arr2.nbytes)
print('内存存储方式',arr2.flags)

2维数组的形状: (2, 3)
2维数组维度: 2
2维数组元素个数: 6
2维数组元素数据类型: float64
2维数组的转置 [[1. 3.]
 [2. 4.]
 [4. 5.]]
单个元素占用的内存字节数 8
数组总内存占用 48
内存存储方式   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## 3.ndarray创建方法

In [8]:
# 基础创建方法
list = [[1,2,3],[4,5,6]]
arr = np.array(list, dtype=np.float64) #可以使用dtype参数指定元素数据类型
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [9]:
# copy
arr_copy = np.copy(arr) # 仅复制数组内容
print(arr_copy)
arr[0][0] = 8.0
print(arr_copy)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [10]:
# 预定义形状
# 全0 全1 未初始化 固定值
arr = np.zeros((2,3))
print(arr)
print(arr.dtype) # 默认float64
arr1 = np.zeros((2,3), dtype=np.int64)
print(arr1.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
int64


In [11]:
arr = np.zeros((10,), dtype=np.int64)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [12]:
#全1
arr = np.ones((10,), dtype=np.int64)
print(arr)

[1 1 1 1 1 1 1 1 1 1]


In [13]:
#未初始化
arr = np.empty((3,)) #数值随机
print(arr)

[2.26995268e-284 3.68918987e-304 1.48625108e-072]


In [14]:
# 固定值
arr = np.full((3,4), 5, dtype=np.float64)
print(arr)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [15]:
arr = np.full((3,4), 5, dtype=np.int64)
arr_z = np.zeros_like(arr) # 使用arr的形状和元素类型
print(arr_z)
arr_o = np.ones_like(arr)
print(arr_o)
arr_e = np.empty_like(arr)
print(arr_e)
arr_f = np.full_like(arr, 6.0) # 虽然使用6.0, 但创建该数组依旧使用arr的元素类型
print(arr_f)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[4617315517961601024 4617315517961601024 4617315517961601024
  4617315517961601024]
 [4617315517961601024 4617315517961601024 4617315517961601024
  4617315517961601024]
 [4617315517961601024 4617315517961601024 4617315517961601024
  4617315517961601024]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [16]:
# 等差数列数组
arr = np.arange(1,9,2) # start, end, step 不包含end
print(arr)

[1 3 5 7]


In [17]:
# 等间隔数组
arr = np.linspace(0,10,5) #把0到10等分
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [18]:
# 对数间隔数组
arr = np.logspace(0,4,3,base=2) # 计算以2为底的指数
print(arr)

[ 1.  4. 16.]


In [19]:
# 特殊矩阵
# 单位矩阵：主对角线上的元素为1，其余元素都为0
arr = np.eye(3,dtype=np.int64)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [20]:
# 对角矩阵: 主对角线上的元素不全为0, 其余元素全为0
arr = np.diag([1,2,2])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 2]]


In [21]:
# 随机矩阵:
arr = np.random.rand(2,3) # 随机数默认0-1
print(arr)

[[0.87081893 0.84685623 0.93126647]
 [0.85041187 0.75404492 0.84801628]]


In [22]:
# 随机浮点数矩阵 指定随机数范围:
arr = np.random.uniform(2,5,(2,3))
print(arr)

[[4.63552308 4.61082553 3.5883372 ]
 [2.84899099 2.94365318 4.51060825]]


In [23]:
# 随机整数矩阵 指定随机数范围:
arr = np.random.randint(2,5,(2,3))
print(arr)

[[4 2 2]
 [2 4 3]]


In [24]:
# 随机矩阵 元素服从标准正态分布: 元素主要分布在-3 - 3之间
arr = np.random.randn(2,5)
print(arr)

[[-1.40541091 -0.92472768  0.79108182  0.45131045  0.51625578]
 [-0.38054768 -0.40993307  0.87386419 -0.71346458 -0.61998481]]


In [25]:
# 设置随机种子
np.random.seed(30)
arr = np.random.randint(2,10,(2,3))
print(arr)

[[7 7 7]
 [7 6 6]]


## 4. ndarray的数据类型

In [ ]:
#bool int unit float complex 布尔 整形 无符号整型 浮点 复数

In [6]:
arr = np.array([1,0,2],dtype=np.bool)
print(arr)
arr1 = np.array([1,2,127],dtype=np.int8)
print(arr1)

[ True False  True]
[  1   2 127]


In [7]:
# 创建复数数组
complex_array = np.array([1 + 2j, 3 + 4j, 5 - 6j],dtype=np.complex64)
print("复数数组:", complex_array)

# 获取实部和虚部
real_part = np.real(complex_array)
imag_part = np.imag(complex_array)
print("实部:", real_part)
print("虚部:", imag_part)

复数数组: [1.+2.j 3.+4.j 5.-6.j]
实部: [1. 3. 5.]
虚部: [ 2.  4. -6.]


In [8]:
real = np.array([1, 2, 3])
imag = np.array([4, 5, 6])
array2 = real + 1j * imag
print("组合后的复数数组:", array2)

a = np.array([1 + 2j, 3 + 4j])
b = np.array([5 - 6j, -7 + 8j])
result = a + b
print("加法结果:", result)



组合后的复数数组: [1.+4.j 2.+5.j 3.+6.j]
加法结果: [ 6. -4.j -4.+12.j]


In [9]:
conjugate_array = np.conjugate(complex_array)
print("共轭数组:", conjugate_array)

共轭数组: [1.-2.j 3.-4.j 5.+6.j]


In [10]:
magnitude = np.abs(complex_array)
print("模长:", magnitude)

模长: [2.236068  5.        7.8102493]


# 5. 索引与切片

In [30]:
# 一维数组
np.random.seed(43)
arr = np.random.randint(1,100,(10,))
print(arr)
print(arr[1])
print(arr[:]) # 获取全部数据
print(arr[2:5]) #不包括5 也可以加步长
print(arr[slice(2,5, 2)]) # start stop step
print(arr[(arr>50) & (arr<60)]) # 布尔索引
print(arr[(arr<50) | (arr>90)])

[69 65 50 22 59 17 52 18 60 92]
65
[69 65 50 22 59 17 52 18 60 92]
[50 22 59]
[50 59]
[59 52]
[22 17 18 92]


In [31]:
# 二维数组
np.random.seed(43)
arr = np.random.randint(1,100,(3,4))
print(arr)
print(arr[1][2])
print(arr[1,2])

[[69 65 50 22]
 [59 17 52 18]
 [60 92 67 31]]
52
52


In [32]:
print(arr[0:2,0:2])
print(arr[0:2][0:2]) # 此处暂时没搞明白
print(arr[0][0:2])

[[69 65]
 [59 17]]
[[69 65 50 22]
 [59 17 52 18]]
[69 65]


In [42]:
print(arr[arr<50])
print(arr[0,arr[0]<50])
print(arr[arr[:,2]<60,2])

[22 17 18 31]
[22]
[50 52]
