In [ ]:
'''
题目1: 温度数据分析
某城市一周的最高气温(℃)为[28, 30, 39, 31, 32, 30, 29]
- 计算平均气温、最高气温和最低气温
- 找出气温超过30℃的天数
'''

In [3]:
import numpy as np
temps = np.array([28, 30, 39, 31, 32, 30, 29], dtype=np.float32)
print('平均气温: ', '%.1f'%np.mean(temps)) # 保留一位小数
print('最高气温: ', np.max(temps))
print('最低气温: ', np.min(temps))
print('气温超过30℃的天数: ', np.sum(temps > 30))
print(len(temps[temps > 30]))


平均气温:  31.3
最高气温:  39.0
最低气温:  28.0
气温超过30℃的天数:  3
3


In [ ]:
'''
题目2: 学生成绩统计
某班级5名学生的数学成绩为[85, 90, 78, 92, 88]
- 计算成绩的平均分、中位数和标准差
- 将成绩转换为十分制
'''

In [10]:
scores = np.array([85, 90, 78, 92, 88])
print('平均分:',np.mean(scores))
print('中位数:',np.median(scores))
print('标准差:','%.2f'%np.std(scores))
print('十分制成绩:',scores/10)

平均分: 86.6
中位数: 88.0
标准差: 4.88
十分制成绩: [8.5 9.  7.8 9.2 8.8]


In [ ]:
'''
题目3: 矩阵运算
给顶矩阵 A = [[1, 2],[3,4]] 和 B = [[5,6],[7,8]]
- 计算 A+B 和 A*B(逐元素相乘)
- 计算A和B的矩阵乘法
'''

In [11]:
A = np.array([[1,2],
              [3,4]], dtype=np.int8)
B = np.array([[5,6],
              [7,8]], dtype=np.int8)
print(A+B)
print(A*B)
print(A@B)


[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
'''
题目4: 随机数生成
生成一个(3,4)的随机整数数组, 范围[0,10)
- 计算每列最大值和每行最小值
- 将数组中所有的奇数替换为-1
'''

In [16]:
np.random.seed(37)
arr_ran = np.random.randint(0,10,size=(3,4))
print(arr_ran)
print('每列最大值:', np.max(arr_ran, axis=0)) # 按列去取最大值
print('每行最小值:', np.min(arr_ran, axis=1)) # 按行去取最小值
print(np.where(arr_ran%2 == 1, -1, arr_ran))
arr_ran[arr_ran%2 == 1] = -1
print(arr_ran)

[[5 6 3 3]
 [5 8 5 7]
 [8 8 3 2]]
每列最大值: [8 8 5 7]
每行最小值: [3 5 2]
[[-1  6 -1 -1]
 [-1  8 -1 -1]
 [ 8  8 -1  2]]
[[-1  6 -1 -1]
 [-1  8 -1 -1]
 [ 8  8 -1  2]]


In [ ]:
'''
题目5: 数组变形
创建一个1到12的一维数组, 并转换为(3,4)的二维数组
- 计算每行和每列的平均值
- 将数组展平为一维数组
'''

In [4]:
import numpy as np
arr = np.arange(1,13)
arr_new = np.resize(arr,(3,4))
print(arr_new)
print(np.mean(arr_new,axis=1)) # 行平均值


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 2.5  6.5 10.5]


In [ ]:
'''
题目6: 生成一个(5,5)的随机数组, 范围[0,20)
- 找出数组中大于10的元素
- 将所有大于10的元素替换为0
'''

In [6]:
arr = np.arange(0,20).reshape(4,5)
print(arr)
print(arr[arr>10])
print(np.where(arr>10, 0, arr))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  0  0  0  0]
 [ 0  0  0  0  0]]


In [ ]:
'''
题目7: 统计函数应用
某公司6个月的销售额为[120,135,110,125,130,140]
- 计算销售额的总和、均值和方差
- 找出销售额最高的月份和最低的月份
'''

In [8]:
arr = np.array([120,135,110,125,130,140])
print(np.sum(arr))
print('%.2f'%np.mean(arr))
print('%.2f'%np.var(arr))
print(np.argmax(arr))
print(np.argmin(arr))

760
126.67
97.22
5
2


In [ ]:
'''
题目8: 数组拼接
给定 A = [1,2,3] 和 B = [4,5,6]
- 将A和B水平拼接为一个新数组
- 将A和B垂直拼接为一个新数组
'''

In [9]:
A = np.array([1,2,3])
B = np.array([4,5,6])
print(np.concatenate((A,B)))
print(np.concatenate((A,B)).reshape(2,3))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
'''
题目9: 唯一值与排序
给定数组[2,1,2,3,1,4,3]
- 找出数组中的唯一值并排序
- 计算每个唯一值出现的次数
'''

In [11]:
arr = np.array([2,1,2,3,1,4,3])
u_arr, counts = np.unique(arr, return_counts=True)
print(u_arr)
print(counts)


[1 2 3 4]
[2 2 2 1]


In [ ]:
'''
题目10:
某商店5天的销售额和成本如下:
销售额: [20,25,22,30,28]
成本: [15,18,16,22,20]
- 计算每天的利润
- 计算平均利润和标准差
- 找出利润最高的天数
'''

In [14]:
sold = np.array([20,25,22,30,28])
cost = np.array([15,18,16,22,20])
save = sold-cost
print('每天利润:',save)
print('平均利润:',save.mean())
print('利润标准差:','%.2f'%save.std())
print('利润最高天数:', (save==save.max()).sum())

每天利润: [5 7 6 8 8]
平均利润: 6.8
利润标准差: 1.17
利润最高天数: 2
