In [ ]:
'''
题目1: 温度数据分析
某城市一周的最高气温(℃)为[28, 30, 39, 31, 32, 30, 29]
- 计算平均气温、最高气温和最低气温
- 找出气温超过30℃的天数
'''

In [3]:
import numpy as np
temps = np.array([28, 30, 39, 31, 32, 30, 29], dtype=np.float32)
print('平均气温: ', '%.1f'%np.mean(temps)) # 保留一位小数
print('最高气温: ', np.max(temps))
print('最低气温: ', np.min(temps))
print('气温超过30℃的天数: ', np.sum(temps > 30))
print(len(temps[temps > 30]))


平均气温:  31.3
最高气温:  39.0
最低气温:  28.0
气温超过30℃的天数:  3
3


In [ ]:
'''
题目2: 学生成绩统计
某班级5名学生的数学成绩为[85, 90, 78, 92, 88]
- 计算成绩的平均分、中位数和标准差
- 将成绩转换为十分制
'''

In [10]:
scores = np.array([85, 90, 78, 92, 88])
print('平均分:',np.mean(scores))
print('中位数:',np.median(scores))
print('标准差:','%.2f'%np.std(scores))
print('十分制成绩:',scores/10)

平均分: 86.6
中位数: 88.0
标准差: 4.88
十分制成绩: [8.5 9.  7.8 9.2 8.8]


In [ ]:
'''
题目3: 矩阵运算
给顶矩阵 A = [[1, 2],[3,4]] 和 B = [[5,6],[7,8]]
- 计算 A+B 和 A*B(逐元素相乘)
- 计算A和B的矩阵乘法
'''

In [11]:
A = np.array([[1,2],
              [3,4]], dtype=np.int8)
B = np.array([[5,6],
              [7,8]], dtype=np.int8)
print(A+B)
print(A*B)
print(A@B)


[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
'''
题目4: 随机数生成
生成一个(3,4)的随机整数数组, 范围[0,10)
- 计算每列最大值和每行最小值
- 将数组中所有的奇数替换为-1
'''

In [16]:
np.random.seed(37)
arr_ran = np.random.randint(0,10,size=(3,4))
print(arr_ran)
print('每列最大值:', np.max(arr_ran, axis=0)) # 按列去取最大值
print('每行最小值:', np.min(arr_ran, axis=1)) # 按行去取最小值
print(np.where(arr_ran%2 == 1, -1, arr_ran))
arr_ran[arr_ran%2 == 1] = -1
print(arr_ran)

[[5 6 3 3]
 [5 8 5 7]
 [8 8 3 2]]
每列最大值: [8 8 5 7]
每行最小值: [3 5 2]
[[-1  6 -1 -1]
 [-1  8 -1 -1]
 [ 8  8 -1  2]]
[[-1  6 -1 -1]
 [-1  8 -1 -1]
 [ 8  8 -1  2]]
